// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_tsissmad_TMBExports
#include <TMB.hpp>
#include "issm.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "issm") {
    return issm(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
