// Generated by TMBtools: do not edit by hand
#define TMB_LIB_INIT R_init_tsissmad_TMBExports
#include <TMB.hpp>
#include "issma.hpp"
#include "issmb.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "issma") {
    return issma(this);
  } else if (model == "issmb"){
    return issmb(this);
  } else{
    error("Unknown model.");
  }
  return 0;
}
